rockchip64-7.2: fix pwmv4 build against new device flag accessors
Linux 7.2 turned the struct device bools into flag accessors
(__create_dev_flag_accessors); direct member access no longer builds:

  drivers/pwm/pwm-rockchip-v4.c:292:20: error: 'struct device' has no
  member named 'of_node_reused'

Use dev_set_of_node_reused() in the 7.2 copy of the patch. Checked the
other 13 patches for the converted flags - this was the only use.

Signed-off-by: crackerjacques <jack@supremeoverlordjabs.co>