main-config: HACK: disable EXTRAWIFI completely for kernels 6.15+ (move to extra_config)
wifi: HACK: drop `rtl8192eu` until we can fix `rtw_cmd.c:17:10: fatal error: drv_types.h: No such file`

```
   drivers/net/wireless/rtl8192eu/core/rtw_cmd.c:17:10: fatal error: drv_types.h: No such file or directory
      17 | #include <drv_types.h>
         |          ^~~~~~~~~~~~~

```

wifi: HACK: drop `driver_rtl8189ES` until we can fix `core/rtw_cmd.c:17:10: fatal error: drv_types.h: No such file`

```
   drivers/net/wireless/rtl8189es/core/rtw_cmd.c:17:10: fatal error: drv_types.h: No such file or directory
      17 | #include <drv_types.h>
         |          ^~~~~~~~~~~~~
```